import type { ChatTemplate } from '@/types/hub';

export const templates: ChatTemplate[] = [
  {
    id: 'new-customer',
    icon: 'UserPlus',
    title: 'לקוח חדש',
    description: 'הוסף לקוח חדש למערכת',
    category: 'customer',
    color: 'from-blue-500 to-blue-600',
    prompt: 'אני רוצה להוסיף לקוח חדש',
    linkedTool: '/customers/new',
  },
  {
    id: 'xray-analysis',
    icon: 'ScanSearch',
    title: 'ניתוח X-RAY',
    description: 'ניתוח עומק של תיק ביטוח',
    category: 'analysis',
    color: 'from-red-500 to-red-600',
    prompt: 'אני רוצה לעשות ניתוח X-RAY לתיק לקוח',
    linkedTool: '/x-ray',
  },
  {
    id: 'wise-recommendations',
    icon: 'Lightbulb',
    title: 'המלצות WISE',
    description: 'המלצות חכמות על בסיס ניתוח',
    category: 'analysis',
    color: 'from-amber-500 to-amber-600',
    prompt: 'אני רוצה לראות המלצות WISE',
    linkedTool: '/wise',
  },
  {
    id: 'stage-quote',
    icon: 'FileText',
    title: 'הצעת מחיר STAGE',
    description: 'צור ושלח הצעת מחיר',
    category: 'policy',
    color: 'from-purple-500 to-purple-600',
    prompt: 'אני רוצה ליצור הצעת מחיר ב-STAGE',
    linkedTool: '/stage',
  },
  {
    id: 'pulse-kpi',
    icon: 'BarChart3',
    title: 'ביצועים PULSE',
    description: 'מדדים ודוחות ביצוע',
    category: 'workflow',
    color: 'from-rose-500 to-rose-600',
    prompt: 'אני רוצה לראות את הביצועים שלי ב-PULSE',
    linkedTool: '/pulse',
  },
  {
    id: 'desk-service',
    icon: 'Headphones',
    title: 'שירות DESK',
    description: 'נהל פניות ותביעות',
    category: 'customer',
    color: 'from-cyan-500 to-cyan-600',
    prompt: 'אני רוצה לפתוח פנייה ב-DESK',
    linkedTool: '/desk',
  },
  {
    id: 'sign-document',
    icon: 'PenTool',
    title: 'חתימה SIGN',
    description: 'חתימה דיגיטלית על מסמכים',
    category: 'document',
    color: 'from-emerald-500 to-emerald-600',
    prompt: 'אני רוצה לחתום על מסמך ב-SIGN',
    linkedTool: '/sign',
  },
  {
    id: 'meeting',
    icon: 'Calendar',
    title: 'פגישה',
    description: 'תזמן או נהל פגישות',
    category: 'meeting',
    color: 'from-indigo-500 to-indigo-600',
    prompt: 'אני רוצה לתאם פגישה עם לקוח',
    linkedTool: '/meetings',
  },
];
